services:
  mariadb:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uyulala
  uyulala:
    container_name: uyulala
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uyulala.compose.yml:/etc/uyulala/uyulala.yml
    ports:
      - 80:8080
    depends_on:
      - mariadb
  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - 3000:3000
    environment:
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "demo"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "demo"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "http://localhost/authorize"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "http://uyulala:8080/api/v1/collect"
      GF_AUTH_GENERIC_OAUTH_API_URL: "http://uyulala:8080/api/v1/oidc/userinfo"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid"
      GF_AUTH_GENERIC_OAUTH_AUTH_STYLE: "InHeader"
      GF_AUTH_GENERIC_OAUTH_NAME: "Uyulala"
      GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: "true"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "'Admin'"
      GF_AUTH_GENERIC_OAUTH_AUTO_LOGIN: "true"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "http://localhost/demo"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
