services:
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uyulala
    ports:
      - 3306:3306
  uyulala:
    container_name: uyulala
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uyulala.compose.yml:/etc/uyulala/uyulala.yml
      - ./tls:/tls
    ports:
      - 443:8080
    depends_on:
      - mariadb

