name: Deploy Dev
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed
jobs:
  Deploy:
    name: Deploy to Dev
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: danielr1996/envsubst-action@1.0.0
        with:
          input: manifests/deployment.dev.yml
          output: deployment.yml
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f manifests/deployment.dev.yml
