name: Docker
on:
  push:
    branches: [ "main" ]
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: "Checkout"
    - uses: docker/setup-qemu-action@v3
      name: "Setup QEMU"
    - uses: docker/setup-buildx-action@v3
      name: Setup docker buildx
    - uses: docker/login-action@v3
      name: Docker login GHCR
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PASSWORD }}
    - uses: docker/build-push-action@v5
      name: Build the Docker image
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        dockerfile: docker/Dockerfile
        push: true
        tags: ghcr.io/daedaluz/uyulala:latest
